- name: variables
  hosts: local
  connection: local
  private: false
  vars_prompt:
    - name: course
      
      prompt: enter the course name
      private: false    
    - name: duration
      
      prompt: enter duration of the course
      private: false
    - name: trainer
      
      prompt: enter the name of the trainer
      private: false
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{course}}, durations of the course is {{duration}}, and the trainer is {{trainer}}"