- name: variables
  hosts: local
  connection: local
  private: false
  vars_prompt:
    - name: course
      private: false
      prompt: enter the course name

    - name: duration
      private: false
      prompt: enter duration of the course
    - name: trainer
      private: false
      prompt: enter the name of the trainer
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{course}}, durations of the course is {{duration}}, and the trainer is {{trainer}}"