- name: variables
  hosts: local
  connection: local
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{course}}, durations of the course is {{duration}}, and the trainer is {{trainer}}"