- name: devops
  hosts: local
  connection: local
  vars:
    course_name: devops
    duration: 120
    trainer: shiva
    topics:
    - linux
    - shell
    - ansible
    - aws
    live: true
    tools:
      ci: jenkins
      cloud: aws
      containerization: docker
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "hello I am learning {{course_name}}, duration {{duration}}, and trainer is {{trainer}}, topics are {{topics}}, and tools used are {{tools}}, and it is live {{live}}"