- name: conditions
  hosts: local
  vars:
    number: 15
  tasks:
  - name: check conditions
    ansible.builtin.debug:
      msg: " check the given number {{number}} is less than 10 "
    when: number < 10
  - name: check conditions
    ansible.builtin.debug:
      msg: " check the given number {{number}} is greater than 10"
    when: number > 10