- name: handling undefined variables
  hosts: local
  connection: local
  tasks:
  - name: H.U.variables
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"
  - name: convert string to list
    ansible.builtin.debug:
    vars:
       fruites: "banana , apple , grapes"
    #ansible.builtin.debug:
      msg: "fruites are conveted into list {{ fruites | split(',') }}"
    