- name: handling undefined variables
  hosts: local
  connection: local
  tasks:
  - name: H.U.variables
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"
  - name: convert string to list
    vars:
       fruites: "banana , apple , grapes"
    ansible.builtin.debug:
      msg: "fruites are conveted into list {{ fruites | split(',') }}"
  - name: convert maps to list
    vars:
      course: devops
      duration: 120
      trainer: shiva
    ansible.builtin.debug:
      msg: " course info {{course | dict2item }}"