- name: handling undefined variables
  hosts: local
  connection: local
  tasks:
  - name: H.U.variables
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"
  - name: convert string to list
    vars:
       fruites: "banana , apple , grapes"
    ansible.builtin.debug:
      msg: "fruites are conveted into list {{ fruites | split(',') }}"
  - name: convert maps to list
    vars:
      course:
        name: devops
        duration: 120
        trainer: shiva
    ansible.builtin.debug:
      msg: " course info {{ course | dict2items }}"
  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'devops'}
      - {'key': 'duration', 'value': '120'}
      - {'key': 'trainer', 'value': 'shiva'}
    ansible.builtin.debug:
      msg: "converted list to map are {{ course | items2dict }}"
  - name: convert upper to lower case
    vars:
      name: "KISHAN"
    ansible.builtin.debug:
      msg: "the conversion is : {{ name | lower }}"
  - name: convert lower to upper case
    vars:
      name: "kishan"
    ansible.builtin.debug:
      msg: "the conversion is : {{ name | upper }}"

  - name: min to max
    vars:
      numbers: [8,4,93,736,]
    ansible.builtin.debug:
      msg: "{{ numbers | max }}"
  - name: max to min
    vars:
      numbers: [8,4,93,736,]
    ansible.builtin.debug:
      msg: "{{ numbers | min }}"